BumboApp/Bumbo.App.Web/Controllers/DayOverviewController.cs
using Bumbo.App.Web.Models.ViewModels.Dayoverview;
using Bumbo.App.Web.Models.ViewModels.Home;
using Bumbo.Data.Context;

using Bumbo.Data.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace Bumbo.App.Web.Controllers
{
	public class DayOverviewController : Controller
	{
		private readonly BumboDbContext _context;

        private readonly ILogger<DayOverviewController> _logger;

        public DayOverviewController(BumboDbContext context, ILogger<DayOverviewController> logger)
		{
			_context = context;
            _logger = logger;

        }

        public async Task<IActionResult> Index(string? date, string? search)
        {
            _logger.LogInformation("open action triggered...");

            DateTime selectedDate;
            if (string.IsNullOrEmpty(date) || !DateTime.TryParse(date, out selectedDate))
            {
                selectedDate = DateTime.Today;
            }

            var employees = await _context.Employees.ToListAsync();
            var workSchedules = await _context.WorkSchedules
                .Where(ws => ws.Date == DateOnly.FromDateTime(selectedDate))
                .ToListAsync();

            var workShifts = await _context.WorkShifts
                .Where(ws => ws.StartTime.Date == selectedDate)
                .ToListAsync();

            var viewModel = employees
                .Where(e => string.IsNullOrEmpty(search) ||
                            e.FirstName.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                            e.LastName.Contains(search, StringComparison.OrdinalIgnoreCase))
                .Select(e => new DayOverviewViewModel
                {
                    EmployeeId = e.EmployeeId,
                    FirstName = e.FirstName,
                    LastName = e.LastName,
                    PlannedHours = workSchedules
                        .Where(ws => ws.EmployeeId == e.EmployeeId)
                        .Sum(ws => (decimal)(ws.EndTime - ws.StartTime).TotalHours),
                    WorkedHoursString = TimeSpan.FromMinutes(
                        workShifts
                        .Where(ws => ws.EmployeeId == e.EmployeeId)
                        .Sum(ws => (ws.EndTime - ws.StartTime)?.TotalMinutes ?? 0))
                        .ToString(@"hh\:mm") ?? "00:00",
                    Shifts = workShifts
                        .Where(ws => ws.EmployeeId == e.EmployeeId)
                        .Select(ws => new ShiftViewModel
                        {
                            StartTime = ws.StartTime.ToString("hh:mm"),
                            EndTime = ws.EndTime?.ToString("hh:mm") ?? "N/A"
                        }).ToList()
                })
                .ToList();

            ViewData["Date"] = DateOnly.FromDateTime(selectedDate);
            ViewData["Search"] = search;
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Save(List<DayOverviewViewModel> updatedHours, DateOnly date)
        {
            _logger.LogInformation("Save action triggered...");

            foreach (var update in updatedHours)
            {
                if (!TimeSpan.TryParse(update.WorkedHoursString, out var workedTimeSpan))
                {
                    _logger.LogWarning($"Invalid time format for EmployeeId {update.EmployeeId}. Skipping...");
                    continue;
                }

                var workShifts = await _context.WorkShifts
                    .Where(ws => ws.EmployeeId == update.EmployeeId && ws.StartTime.Date == date.ToDateTime(TimeOnly.MinValue).Date)
                    .ToListAsync();

                if (workedTimeSpan == TimeSpan.Zero && workShifts.Any())
                {
                    _logger.LogInformation($"EmployeeId {update.EmployeeId} has no worked hours. Removing all shifts...");
                    _context.WorkShifts.RemoveRange(workShifts);
                    continue;
                }

                if (workShifts.Any())
                {
                    var totalExistingWorkedTime = workShifts.Skip(1).Sum(ws => (ws.EndTime - ws.StartTime)?.TotalMinutes ?? 0);
                    var remainingWorkedMinutes = workedTimeSpan.TotalMinutes - totalExistingWorkedTime;

                    if (remainingWorkedMinutes > 0)
                    {
                        var firstShift = workShifts.First();
                        firstShift.EndTime = firstShift.StartTime.AddMinutes(remainingWorkedMinutes);
                        _context.WorkShifts.Update(firstShift);
                    }
                    else
                    {
                        _logger.LogWarning($"Total worked time is less than existing shifts' time for EmployeeId {update.EmployeeId}. Skipping update.");
                        continue;
                    }
                }
                else
                {
                    var newWorkShift = new WorkShift
                    {
                        EmployeeId = update.EmployeeId,
                        StartTime = date.ToDateTime(TimeOnly.MinValue.AddHours(8)),
                        EndTime = date.ToDateTime(TimeOnly.MinValue.AddHours(8)).Add(workedTimeSpan)
                    };
                    _context.WorkShifts.Add(newWorkShift);
                }
            }

            await _context.SaveChangesAsync();

            
            TempData["SuccessMessage"] = "Wijzigingen succesvol opgeslagen!";
            return RedirectToAction("Index", new { date });
        }




    }
}

BumboApp/Bumbo.App.Web/Controllers/LeaveController.cs
using Bumbo.App.Web.Models.ViewModels.Leave;
using Bumbo.App.Web.Models.ViewModels.LeaveRequest;
using Bumbo.Data.Models.LeaveModel;
using Bumbo.Data.Interfaces;
using Bumbo.Data.Models;
using Bumbo.Domain.Services.Leaves;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.Design;
using Microsoft.VisualBasic;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bumbo.App.Web.Controllers
{
    [Authorize]
    public class LeaveController : Controller
    {
        private readonly ILeaveRepository repo;
        private readonly ILeaveChecker lRepo;
        private readonly IEmployeeRepository empRepo;

        public LeaveController(ILeaveRepository repo, ILeaveChecker lRepo, IEmployeeRepository empRepo)
        {
            this.repo = repo;
            this.lRepo = lRepo;
            this.empRepo = empRepo;
        }
        public IActionResult Index(int employeeId)
        {
            LeaveRequestModel viewModel = new LeaveRequestModel();
            viewModel.start = DateOnly.FromDateTime(DateTime.Now);
            viewModel.end = viewModel.start;
            viewModel.myRequests = repo.getAllRequestsOfEmployee(employeeId);
            viewModel.employeeId = employeeId; 

            viewModel.status = "Requested";

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Index(LeaveRequestModel viewModel)
        {
            if (viewModel.employeeId == 0)
            {
                TempData["FailedMessage"] = "EmployeeId ontbreekt!";
                return RedirectToAction("Index");
            }

            Leave newRequest = new Leave
            {
                EmployeeId = viewModel.employeeId,
                StartDate = viewModel.start,
                EndDate = viewModel.end,
                LeaveStatus = viewModel.status
            };
            int check = lRepo.doAllChecks(newRequest);

            switch (check)
            {
                case 0:
                    TempData["SuccessMessage"] = $"Verlof is aangevraagd!";
                    repo.SetLeaveRequest(newRequest);
                    break;
                case 1:
                    TempData["FailedMessage"] = $"Kan geen verlof aanvragen voor vandaag of eerdere datums!";
                    break;
                case 2:
                    TempData["FailedMessage"] = $"Start datum mag niet hoger zijn dan de eind datum!";
                    break;
                case 3:
                    TempData["FailedMessage"] = $"Er is al verlof aangevraagd op deze datum!";
                    break;
                default:
                    TempData["FailedMessage"] = $"Onbekende fout bij het aanvragen van verlof!";
                    break;
            }
            return RedirectToAction("Index", new { employeeId = viewModel.employeeId });
        }

        public IActionResult MyRequest()
        {
            int employeeID = 1;
            AllLeaveRequestsModel viewModel = new AllLeaveRequestsModel();
            viewModel.myRequests = new List<LeaveRequestModel>(); 

            var requests = repo.getAllRequestsOfEmployee(employeeID);

            foreach (var request in requests)
            {
                LeaveRequestModel model = new LeaveRequestModel(); 
                model.employeeId = employeeID;
                model.start = request.StartDate;
                model.end = request.EndDate;
                model.status = request.LeaveStatus;
                viewModel.myRequests.Add(model);
            }

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult LeaveManagement(string? firstDayOfWeek)
        {
            AllLeaveRequestsModel viewModel = new AllLeaveRequestsModel();
            viewModel.myRequests = new List<LeaveRequestModel>();
            viewModel.myRequestsList = new List<List<Bumbo.Data.Models.LeaveModel.LeaveOverviewDTO>>();

            DateTime today = DateTime.Today; ;
            if (firstDayOfWeek != null)
            {
                today = DateTime.ParseExact(firstDayOfWeek, "dd-MM-yyyy", System.Globalization.CultureInfo.InvariantCulture);
            }

            viewModel.startOfWeek = today.AddDays(-(int)today.DayOfWeek + (int)DayOfWeek.Monday);
            viewModel.weekDates = new List<DateTime>();

            for (int i = 0; i < 7; i++)
            {
                viewModel.weekDates.Add(viewModel.startOfWeek.AddDays(i));
            }
            viewModel.endOfWeek = viewModel.weekDates[6];
            DateOnly firstDay = new DateOnly(viewModel.weekDates[0].Year, viewModel.weekDates[0].Month, viewModel.weekDates[0].Day);
            DateOnly lastDay = new DateOnly(viewModel.weekDates[6].Year, viewModel.weekDates[6].Month, viewModel.weekDates[6].Day);


            viewModel.leaves = repo.getAllLeaves(firstDay, lastDay);

            var requests = repo.getAllPendingRequests();
            foreach (var request in requests)
            {
                LeaveRequestModel model = new LeaveRequestModel();
                model.employeeId = request.EmployeeId;
                model.employeeName = empRepo.FindNameFromId(request.EmployeeId);
                model.start = request.StartDate;
                model.end = request.EndDate;
                model.status = request.LeaveStatus;
                viewModel.myRequests.Add(model);
            }
            List<int> employeeIdList = repo.getEmployeesInLeave();
            List<Bumbo.Data.Models.LeaveModel.LeaveOverviewDTO> models = new List<LeaveOverviewDTO>();
            models = viewModel.leaves;
            foreach ( int id in employeeIdList)
            {
                List< Bumbo.Data.Models.LeaveModel.LeaveOverviewDTO > LRM = new List<Bumbo.Data.Models.LeaveModel.LeaveOverviewDTO>();
                for(int i = 0; i < models.Count; i++)
                {
                    if (id == models[i].Id)
                    {
                        LRM.Add(models[i]);
                       
                    }
                }
                viewModel.myRequestsList.Add(LRM);
            }

            viewModel.leaves = repo.getAllLeaves(firstDay, lastDay);
            return View(viewModel);
        }


        [HttpPost]
        public IActionResult Approve(int employeeId, DateOnly start)
        {
            TempData["SuccessMessage"] = $"Verlof is goed gekeurd!";
            Leave leave = repo.getLeaveRequest(employeeId,start);
            leave.LeaveStatus = "Accepted";
            repo.updateLeaveStatus(leave);

            return RedirectToAction("LeaveManagement");
        }

        [HttpPost]
        public IActionResult Reject(int employeeId, DateOnly start )
        {
            TempData["FailedMessage"] = $"Verlof is geweigerd!";
            Leave leave = repo.getLeaveRequest(employeeId, start);
            leave.LeaveStatus = "Denied";
            repo.updateLeaveStatus(leave);
            return RedirectToAction("LeaveManagement");
        }

        public IActionResult AllRequestOverview()
        {
           AllLeaveRequestsModel viewModel = new AllLeaveRequestsModel();
            viewModel.myRequests = new List<LeaveRequestModel>();

            var requests = repo.getAllRequests();
            foreach (var request in requests)
            {
                LeaveRequestModel model = new LeaveRequestModel();
                model.employeeId = request.EmployeeId;
                model.employeeName = empRepo.FindNameFromId(request.EmployeeId);
                model.start = request.StartDate;
                model.end = request.EndDate;
                model.status = request.LeaveStatus;
                viewModel.myRequests.Add(model);
            }


            return View(viewModel);
        }

        public IActionResult Edit(int employeeID, string startdate)
        {
            LeaveRequestModel viewModel = new LeaveRequestModel();
            DateTime dateTime = DateTime.Parse(startdate);
            DateOnly startDate = DateOnly.FromDateTime(dateTime);

            viewModel.StatusOptions = repo.GetLeaveStatuses();


            viewModel.employeeId = employeeID;
            viewModel.employeeName = empRepo.FindNameFromId(employeeID);
            viewModel.start = startDate;
            Leave leave = repo.getLeaveRequest(employeeID, startDate);
            viewModel.end = leave.EndDate;
            viewModel.status = leave.LeaveStatus;

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Edit(LeaveRequestModel viewModel)
        {
            Leave leave = repo.getLeaveRequest(viewModel.employeeId, viewModel.start);
            leave.LeaveStatus = viewModel.status;

            repo.UpdateLeaveRequest(viewModel.employeeId, viewModel.start, viewModel.status);

            viewModel.end = leave.EndDate;

            return RedirectToAction("AllRequestOverview");
        }
    }
}

BumboApp/Bumbo.App.Web/Controllers/NormController.cs
using Bumbo.Data.Interfaces;
using Bumbo.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


namespace BumboApp.Controllers
{
    [Authorize(Roles="manager")]
    public class NormController : Controller
    {
        private readonly INormRepository repo;
        public NormController(INormRepository normRepository)
        {
            this.repo = normRepository;
        }

        public IActionResult Index()
        {
            var model = this.repo.GetAll();
            var branchIds = repo.GetAllUniqueBranchIds();
            ViewBag.BranchIds = branchIds;
            return this.View(model);
        }

        [HttpPost]
        public IActionResult Index(String branchId)
        {
            if (branchId != null)
            {
               
                int value = int.Parse(branchId);
                var model = this.repo.GetAllFromBranch(value);
                var branchIds = repo.GetAllUniqueBranchIds();
                ViewBag.BranchIds = branchIds;
                return this.View(model);
            }
            else
                
            {
                var model1 = this.repo.GetAll();
                var branchIds = repo.GetAllUniqueBranchIds();
                ViewBag.BranchIds = branchIds;
                return this.View(model1);
            }
           
        }

        public IActionResult Edit(int? id, int hour, string activity)
        {
            if (id.HasValue && !string.IsNullOrEmpty(activity))
            {
                var norm = repo.GetOne(id.Value);
                norm.SupermarketActivity = activity;
                norm.NormPerHour = hour;
                return View(norm);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(int id, string activity, Norm norm)
        {
            if (id != norm.BranchId)
            {
                return this.NotFound();
            }
            else
            {
                var model = this.repo.Update(norm);
                return this.RedirectToAction("Index");
            }
            
        }

    }
}

BumboApp/Bumbo.App.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BumboApplicatie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true" />
</head>
<body>
    @if (User.Identity.IsAuthenticated || ViewData["Title"]?.ToString() != "Aanmelden Bumbo")
    {
        <header>
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" asp-route-employeeId="@User.FindFirst("employee_id")?.Value">
                        <img src="~/images/bumbo-logo.png" alt="Bumbo Logo">
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-area=""
                                   asp-controller="Availability"
                                   asp-action="Details"
                                   asp-route-employeeId="@User.FindFirst("employee_id")?.Value"
                                   asp-route-branchId="@User.FindFirst("branch_id")?.Value"
                                >Mijn Beschikbaarheid</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-area=""
                                   asp-controller="SchoolSchedule"
                                   asp-action="Details"
                                   asp-route-employeeId="@User.FindFirst("employee_id")?.Value"
                                >Schoolrooster</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Leave" asp-action="Index" asp-route-employeeId="@User.FindFirst("employee_id")?.Value">Verlof aanvragen</a>
                            </li>

                            @if (User.FindFirst("position")?.Value == "manager")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="managerDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Manager Menu
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="managerDropdown">
                                        <li><a class="dropdown-item" asp-controller="Forecast" asp-action="Index" asp-route-branchId="@User.FindFirst("branch_id")?.Value">Prognose</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Employee" asp-action="Index" asp-route-branchId="@User.FindFirst("branch_id")?.Value">Personeelslijst</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Norm" asp-action="Index">Norm beheer</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Leave" asp-action="LeaveManagement">Verlof beheren</a></li>
                                        <li><a class="dropdown-item" asp-controller="Availability" asp-action="Index" asp-route-branchId="@User.FindFirst("branch_id")?.Value">Beschikbaarheid</a></li>
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Scheduling" asp-action="RoosterRefactored" asp-route-branchId="@User.FindFirst("branch_id")?.Value">Roostering</a></li>
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="DayOverview" asp-action="Index" asp-route-branchId="@User.FindFirst("branch_id")?.Value">Dag overzicht</a></li>
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="MonthOverview" asp-action="Index" asp-route-employeeId="@User.FindFirst("employee_id")?.Value">Maand overzicht</a></li>
                                    </ul>
                                </li>
                            }
                        </ul>
                        <form asp-controller="Account" asp-action="Logout" method="post" class="d-flex">
                            <button type="submit" class="btn-logout">Uitloggen</button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>